### ISSUE TITLE
Could tests be done in bash (or any other language) in addition to C#?

### ISSUE THREAD

**Issue by q2dg** [FherStk/AutoCheck#9]
Thanks!

**Comment by FherStk** [comment]
Hi there!

As the app has been developed using C#, at this moment the only supported "scripting" language is C# but... I will add new functionalities that could help with that:

- Phase 1: A new connector and checker for executing local or remote commands, allowing the execution of bash scripts, external apps, etc. A C# script will still be needed for setting up the scores, the copy detector, messages and so on, but can be as simple as one single line. 

- Phase 2: Using the previous work, it will be provided a new way to run bash scripts directly over a batch of assignments (or a single one). This may be extended for another kind of runnable commands or applications, but I must think how to integrate copy-detector or score calculation capabilities (otherwise, it won't be different as loop inside the main bash script).

Please, be patient (I will take care as soon as I can), and thanks a lot for your suggestion.
Best regards,
Fher

**Comment by FherStk** [comment]
Some documentation must be updated and old C# scripts from v1 must be still converted to YAML scripts for v2... But the first beta for v2 is ready to go :)

**Comment by FherStk** [comment]
Some documentation must be updated and old C# scripts from v1 must be still converted to YAML scripts for v2... But the first beta for v2 is ready to go :)
